### ISSUE TITLE
Text size limit for the Galois Autocompleter API

### ISSUE THREAD

**Issue by GabrielTamujo** [iedmrc/galois-autocompleter#6]
Hi!

While testing Galois, I discovered something that seems to be a limit at the size of the text that you can send to the Autocompleter API without getting a 500 error. I could not find the exactly number, but around 2180 characters of code it starts crashing. 

He are the error logs I got:

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
	 [[{{node sample_sequence/while/model/GatherV2_1}}]]`

**Comment by iedmrc** [comment]
Hey,

Thank you for the bug report. If you have any fix, any PR is welcome. 
Since I'm a bit busy nowadays, I cannot specify any date for the fix.
